import { useAuth } from '@/hooks/useAuth'
import { useBooking } from '@/hooks/useBooking'
import { manualUserSync } from '@/lib/syncUser'
import { Button } from '@/components/ui/button'
import { AlertTriangle } from 'lucide-react'
