# name: Vercel Production Deployment

# on:
#   push:
#     branches:
#       - main

# defaults:
#   run:
#     working-directory: frontend

# env:
#   VERCEL_ORG_ID:      ${{ secrets.VERCEL_ORG_ID }}
#   VERCEL_PROJECT_ID:  ${{ secrets.VERCEL_PROJECT_ID_PRODUCTION }}

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - uses: actions/setup-node@v3
#         with:
#           node-version: 18

#       - name: Install dependencies
#         run: npm ci

#       - name: Run tests
#         run: npm test

#   deploy-production:
#     needs: test
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - name: Install Vercel CLI
#         run: npm install --global vercel

#       - name: Pull Vercel env (prod) (Pull vercel Environment Information)
#         run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

#       - name: Build Project Artifacts
#         run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

#       - name: Deploy Project Artifacts
#         run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
